# Generated by Django 3.1.1 on 2020-10-13 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_csv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attribute',
            name='age',
            field=models.FloatField(),
        ),
    ]
